package main.dogappandroid.Utilities;

public class ProvinceUtils {
    public static int calculateProvincePosition(String province) {
        if (province.equals("Bangkok")) return 0;
        else if (province.equals("Krabi")) return 1;
        else if (province.equals("Kanchanaburi")) return 2;
        else if (province.equals("Kalasin")) return 3;
        else if (province.equals("Kamphaeng Phet")) return 4;
        else if (province.equals("Khon Kaen")) return 5;
        else if (province.equals("Chanthaburi")) return 6;
        else if (province.equals("Chachoengsao")) return 7;
        else if (province.equals("Chon Buri")) return 8;
        else if (province.equals("Chai Nat")) return 9;
        else if (province.equals("Chaiyaphum")) return 10;
        else if (province.equals("Chumphon")) return 11;
        else if (province.equals("Chiang Rai")) return 12;
        else if (province.equals("Chiang Mai")) return 13;
        else if (province.equals("Trang")) return 14;
        else if (province.equals("Trat")) return 15;
        else if (province.equals("Tak")) return 16;
        else if (province.equals("Nakhon Nayok")) return 17;
        else if (province.equals("Nakhon Pathom")) return 18;
        else if (province.equals("Nakhon Phanom")) return 19;
        else if (province.equals("Nakhon Ratchasima")) return 20;
        else if (province.equals("Nakhon Si Thammarat")) return 21;
        else if (province.equals("Nakhon Sawan")) return 22;
        else if (province.equals("Nonthaburi")) return 23;
        else if (province.equals("Narathiwat")) return 24;
        else if (province.equals("Nan")) return 25;
        else if (province.equals("Bueng Kan")) return 26;
        else if (province.equals("Buri Ram")) return 27;
        else if (province.equals("Pathum Thani")) return 28;
        else if (province.equals("Prachuap Khiri Khan")) return 29;
        else if (province.equals("Prachinburi")) return 30;
        else if (province.equals("Pattani")) return 31;
        else if (province.equals("Phra Nakhon Si Ayutthaya")) return 32;
        else if (province.equals("Phang Nga")) return 33;
        else if (province.equals("Phichit")) return 34;
        else if (province.equals("Phatthalung")) return 35;
        else if (province.equals("Phitsanulok")) return 36;
        else if (province.equals("Phetchaburi")) return 37;
        else if (province.equals("Phetchabun")) return 38;
        else if (province.equals("Phrae")) return 39;
        else if (province.equals("Phayao")) return 40;
        else if (province.equals("Phuket")) return 41;
        else if (province.equals("Maha Sarakham")) return 42;
        else if (province.equals("Mukdahan")) return 43;
        else if (province.equals("Mae Hong Son")) return 44;
        else if (province.equals("Yala")) return 45;
        else if (province.equals("Yasothon")) return 46;
        else if (province.equals("Roi Et")) return 47;
        else if (province.equals("Ranong")) return 48;
        else if (province.equals("Rayong")) return 49;
        else if (province.equals("Ratchaburi")) return 50;
        else if (province.equals("Lop Buri")) return 51;
        else if (province.equals("Lampang")) return 52;
        else if (province.equals("Lamphun")) return 53;
        else if (province.equals("Loei")) return 54;
        else if (province.equals("Sisaket")) return 55;
        else if (province.equals("Sakon Nakhon")) return 56;
        else if (province.equals("Songkhla")) return 57;
        else if (province.equals("Satun")) return 58;
        else if (province.equals("Samut Prakan")) return 59;
        else if (province.equals("Samut Songkhram")) return 60;
        else if (province.equals("Samut Sakhon")) return 61;
        else if (province.equals("Sa Kaeo")) return 62;
        else if (province.equals("Saraburi")) return 63;
        else if (province.equals("Sing Buri")) return 64;
        else if (province.equals("Sukhothai")) return 65;
        else if (province.equals("Suphan Buri")) return 66;
        else if (province.equals("Surat Thani")) return 67;
        else if (province.equals("Surin")) return 68;
        else if (province.equals("Nong Khai")) return 69;
        else if (province.equals("Nong Bua Lam Phu")) return 70;
        else if (province.equals("Ang Thong")) return 71;
        else if (province.equals("Udon Thani")) return 72;
        else if (province.equals("Uthai Thani")) return 73;
        else if (province.equals("Uttaradit")) return 74;
        else if (province.equals("Ubon Ratchathani")) return 75;
        else return 76;
    }
}
